name: elm
channels:
  - defaults
  - pytorch
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - aom=3.12.1=h7934f7d_0
  - blas=1.0=mkl
  - bzip2=1.0.8=h5eee18b_6
  - c-ares=1.34.5=hef5626c_0
  - ca-certificates=2025.9.9=h06a4308_0
  - cairo=1.18.4=h44eff21_0
  - contourpy=1.2.1=py39hdb19cb5_1
  - cpuonly=2.0=0
  - cudatoolkit=11.3.1=h2bc3f7f_2
  - cycler=0.11.0=pyhd3eb1b0_0
  - cyrus-sasl=2.1.28=h1110e0f_3
  - dav1d=1.2.1=h5eee18b_0
  - eigen=3.4.0=hdb19cb5_0
  - expat=2.7.1=h6a678d5_0
  - ffmpeg=6.1.1=hc01ab50_4
  - fontconfig=2.15.0=h2c49b7f_0
  - fonttools=4.60.1=py39hee96239_0
  - freetype=2.13.3=h4a9f257_0
  - gflags=2.2.2=h6a678d5_1
  - giflib=5.2.2=h5eee18b_0
  - glog=0.5.0=h6a678d5_1
  - graphite2=1.3.14=h295c915_1
  - gst-plugins-base=1.24.12=hc146dc4_1
  - gstreamer=1.24.12=hb6d4d65_1
  - gstreamer-orc=0.4.41=h5eee18b_0
  - harfbuzz=10.2.0=hdfddeaa_1
  - hdf5=1.14.5=h2b7332f_2
  - icu=73.1=h6a678d5_0
  - importlib_resources=6.5.2=py39h06a4308_0
  - intel-openmp=2023.0.0=h9e868ea_25371
  - jpeg=9f=h5ce9db8_0
  - kiwisolver=1.4.4=py39h6a678d5_0
  - lame=3.100=h7b6447c_0
  - lcms2=2.16=h92b89f2_1
  - ld_impl_linux-64=2.44=h153f514_2
  - leptonica=1.82.0=hfdeec58_3
  - lerc=4.0.0=h6a678d5_0
  - libabseil=20250127.0=cxx17_h6a678d5_0
  - libarchive=3.8.1=h13d4d48_0
  - libcups=2.4.2=h252cb56_2
  - libcurl=8.15.0=hc1efc7f_0
  - libdeflate=1.22=h5eee18b_0
  - libdrm=2.4.124=h5eee18b_0
  - libedit=3.1.20230828=h5eee18b_0
  - libegl=1.7.0=h5eee18b_2
  - libev=4.33=h7f8727e_1
  - libevent=2.1.12=hdbd6064_1
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgfortran-ng=11.2.0=h00389a5_1
  - libgfortran5=11.2.0=h1234567_1
  - libgl=1.7.0=h5eee18b_2
  - libglib=2.84.2=h37c7471_0
  - libglvnd=1.7.0=h5eee18b_2
  - libglx=1.7.0=h5eee18b_2
  - libgomp=11.2.0=h1234567_1
  - libiconv=1.16=h5eee18b_3
  - libkrb5=1.21.3=h520c7b4_4
  - libllvm15=15.0.7=he89c38a_4
  - libnghttp2=1.57.0=h2d74bed_0
  - libogg=1.3.5=h27cfd23_1
  - libopus=1.3.1=h5eee18b_1
  - libpciaccess=0.18=h5eee18b_0
  - libpng=1.6.39=h5eee18b_0
  - libpq=17.6=ha51bf15_0
  - libprotobuf=5.29.3=h3cdef7c_1
  - libsodium=1.0.20=heac8642_0
  - libssh2=1.11.1=h251f7ec_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libtheora=1.2.0=h32ad74f_1
  - libtiff=4.7.0=hde9077f_0
  - libuuid=1.41.5=h5eee18b_0
  - libuv=1.48.0=h5eee18b_0
  - libvorbis=1.3.7=h7b6447c_0
  - libvpx=1.13.1=h6a678d5_0
  - libwebp=1.3.2=h9f374a3_1
  - libwebp-base=1.3.2=h5eee18b_1
  - libxcb=1.17.0=h9b100fa_0
  - libxkbcommon=1.9.1=h69220b7_0
  - libxml2=2.13.8=hfdd30dd_0
  - libzlib=1.3.1=hb25bd0a_0
  - lmdb=0.9.31=hb25bd0a_0
  - lz4-c=1.9.4=h6a678d5_1
  - matplotlib=3.9.2=py39h06a4308_1
  - matplotlib-base=3.9.2=py39hbfdbfaf_1
  - mesalib=25.1.5=h31e3550_0
  - mkl=2023.1.0=h213fc3f_46344
  - mkl-service=2.4.0=py39h5eee18b_2
  - mkl_fft=1.3.11=py39h5eee18b_0
  - mkl_random=1.2.8=py39h1128e8f_0
  - mysql=8.4.0=h721767e_2
  - ncurses=6.5=h7934f7d_0
  - numpy=1.26.4=py39h5f9d8c6_0
  - numpy-base=1.26.4=py39hb5e798b_0
  - opencv=4.10.0=py39h6030d24_7
  - openh264=2.6.0=he621ea3_0
  - openjpeg=2.5.2=h0d4d230_1
  - openldap=2.6.10=he9288cc_1
  - openssl=3.0.18=hd6dcaed_0
  - packaging=25.0=py39h06a4308_0
  - pcre2=10.42=hebb0a14_1
  - pillow=11.1.0=py39hac6e08b_1
  - pip=25.2=pyhc872135_1
  - pixman=0.46.4=h7934f7d_0
  - protobuf=5.29.3=py39he621ea3_0
  - pthread-stubs=0.3=h0ce48e5_1
  - pyparsing=3.2.0=py39h06a4308_0
  - pyqt=6.7.1=py39h8dad735_2
  - pyqt6-sip=13.9.1=py39h6ce4db3_2
  - python=3.9.24=h602e5db_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - pytorch=1.10.0=py3.9_cpu_0
  - pytorch-mutex=1.0=cpu
  - qtbase=6.7.3=h10a5587_4
  - qtdeclarative=6.7.3=h7934f7d_1
  - qtsvg=6.7.3=he4bddd1_1
  - qttools=6.7.3=h5a8de97_1
  - qtwebchannel=6.7.3=h7934f7d_1
  - qtwebsockets=6.7.3=h7934f7d_1
  - readline=8.3=hc2a1206_0
  - setuptools=80.9.0=py39h06a4308_0
  - sip=6.10.0=py39h6a678d5_0
  - six=1.17.0=py39h06a4308_0
  - spirv-tools=2025.1=hdb19cb5_0
  - sqlite=3.50.2=hb25bd0a_1
  - tbb=2021.8.0=hdb19cb5_0
  - tensorboardx=2.6.2.2=py39h06a4308_0
  - tesseract=5.2.0=hb0d2e87_3
  - tk=8.6.15=h54e0aa7_0
  - tomli=2.2.1=py39h06a4308_0
  - torchaudio=0.10.0=py39_cu113
  - torchvision=0.11.0=py39_cu113
  - tornado=6.5.1=py39h5eee18b_0
  - tqdm=4.67.1=py39h2f386ee_0
  - typing_extensions=4.15.0=py39h06a4308_0
  - tzdata=2025b=h04d1e81_0
  - wheel=0.45.1=py39h06a4308_0
  - xcb-util=0.4.1=h5eee18b_2
  - xcb-util-cursor=0.1.5=h5eee18b_0
  - xcb-util-image=0.4.0=h5eee18b_2
  - xcb-util-keysyms=0.4.1=h5eee18b_0
  - xcb-util-renderutil=0.3.10=h5eee18b_0
  - xcb-util-wm=0.4.2=h5eee18b_0
  - xkeyboard-config=2.44=h5eee18b_0
  - xorg-libice=1.1.2=h9b100fa_0
  - xorg-libsm=1.2.6=h9b100fa_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-libxext=1.3.6=h9b100fa_0
  - xorg-libxfixes=6.0.1=h9b100fa_0
  - xorg-libxrandr=1.5.4=h9b100fa_0
  - xorg-libxrender=0.9.12=h9b100fa_0
  - xorg-libxshmfence=1.3.3=h9b100fa_0
  - xorg-libxxf86vm=1.1.6=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - zipp=3.21.0=py39h06a4308_0
  - zlib=1.3.1=hb25bd0a_0
  - zstd=1.5.7=h11fc155_0
  - pip:
      - efficientunet-pytorch==0.0.6
      - torchsummary==1.5.1
prefix: /home/anthos/miniconda3/envs/elm
