name: elm-gpu
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - aom=3.6.0
  - asttokens=3.0.0
  - backcall=0.2.0
  - blas=1.0
  - bzip2=1.0.8
  - c-ares=1.34.5
  - ca-certificates=2025.10.5
  - cairo=1.18.4
  - comm=0.2.1
  - contourpy=1.2.1
  - cudatoolkit=11.8.0
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - dav1d=1.2.1
  - debugpy=1.8.16
  - decorator=5.2.1
  - exceptiongroup=1.3.0
  - executing=2.2.1
  - expat=2.7.1
  - ffmpeg=6.1.1
  - filelock=3.17.0
  - fontconfig=2.15.0
  - fonttools=4.60.1
  - freetype=2.13.3
  - fribidi=1.0.10
  - fsspec=2025.7.0
  - gettext=0.21.0
  - giflib=5.2.2
  - gmp=6.3.0
  - gmpy2=2.2.1
  - graphite2=1.3.14
  - harfbuzz=10.2.0
  - icu=73.1
  - importlib-metadata=8.5.0
  - importlib_metadata=8.5.0
  - importlib_resources=6.5.2
  - ipykernel=6.30.1
  - ipython=8.15.0
  - jedi=0.19.2
  - jinja2=3.1.6
  - jpeg=9f
  - jupyter_client=8.6.3
  - jupyter_core=5.8.1
  - jupyterlab_widgets=3.0.15
  - kiwisolver=1.4.4
  - lame=3.100
  - lcms2=2.16
  - ld_impl_linux-64=2.44
  - leptonica=1.82.0
  - lerc=4.0.0
  - libabseil=20250127.0
  - libarchive=3.8.2
  - libavif=1.1.1
  - libcups=2.4.2
  - libcurl=8.16.0
  - libdeflate=1.22
  - libdrm=2.4.124
  - libedit=3.1.20230828
  - libegl=1.7.0
  - libev=4.33
  - libevent=2.1.12
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgfortran-ng=11.2.0
  - libgfortran5=11.2.0
  - libgl=1.7.0
  - libglib=2.84.2
  - libglvnd=1.7.0
  - libglx=1.7.0
  - libgomp=11.2.0
  - libiconv=1.16
  - libidn2=2.3.8
  - libkrb5=1.21.3
  - libllvm15=15.0.7
  - libnghttp2=1.57.0
  - libnsl=2.0.0
  - libogg=1.3.5
  - libopenblas=0.3.30
  - libopenjpeg=2.5.4
  - libopus=1.3.1
  - libpciaccess=0.18
  - libpng=1.6.50
  - libpq=17.6
  - libprotobuf=5.29.3
  - libsodium=1.0.20
  - libssh2=1.11.1
  - libstdcxx-ng=11.2.0
  - libtheora=1.1.1
  - libtiff=4.7.0
  - libtorch=2.5.1
  - libunistring=1.3
  - libuuid=1.41.5
  - libuv=1.48.0
  - libvorbis=1.3.7
  - libvpx=1.13.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libxcb=1.17.0
  - libxkbcommon=1.9.1
  - libxml2=2.13.9
  - libzlib=1.3.1
  - lmdb=0.9.31
  - lz4-c=1.9.4
  - markupsafe=3.0.2
  - matplotlib=3.9.2
  - matplotlib-base=3.9.2
  - matplotlib-inline=0.1.7
  - mesalib=25.1.5
  - mpc=1.3.1
  - mpfr=4.2.1
  - mpmath=1.3.0
  - mysql=8.4.0
  - ncurses=6.5
  - nest-asyncio=1.6.0
  - networkx=3.2.1
  - nomkl=3.0
  - numpy=2.0.2
  - numpy-base=2.0.2
  - openh264=2.1.1
  - openjpeg=2.5.4
  - openldap=2.6.10
  - openssl=3.0.18
  - opentelemetry-api=1.37.0
  - packaging=25.0
  - parso=0.8.4
  - pcre2=10.42
  - pexpect=4.9.0
  - pickleshare=0.7.5
  - pillow=11.3.0
  - pip=25.2
  - pixman=0.46.4
  - platformdirs=4.3.7
  - prompt-toolkit=3.0.52
  - psutil=7.0.0
  - pthread-stubs=0.3
  - ptyprocess=0.7.0
  - pure_eval=0.2.3
  - pygments=2.19.1
  - pyparsing=3.2.0
  - pyqt=6.7.1
  - pyqt6-sip=13.9.1
  - python=3.9.24
  - python-dateutil=2.9.0post0
  - python_abi=3.9
  - pyzmq=27.1.0
  - qtbase=6.7.3
  - qtdeclarative=6.7.3
  - qtsvg=6.7.3
  - qttools=6.7.3
  - qtwebchannel=6.7.3
  - qtwebsockets=6.7.3
  - readline=8.3
  - setuptools=72.1.0
  - sip=6.10.0
  - six=1.17.0
  - sleef=3.5.1
  - spirv-tools=2025.1
  - sqlite=3.50.2
  - stack_data=0.6.3
  - sympy=1.14.0
  - tesseract=5.2.0
  - tk=8.6.15
  - tomli=2.2.1
  - tornado=6.5.1
  - tqdm=4.67.1
  - traitlets=5.14.3
  - typing-extensions=4.15.0
  - typing_extensions=4.15.0
  - tzdata=2025b
  - wcwidth=0.2.13
  - wheel=0.45.1
  - xcb-util=0.4.1
  - xcb-util-cursor=0.1.5
  - xcb-util-image=0.4.0
  - xcb-util-keysyms=0.4.1
  - xcb-util-renderutil=0.3.10
  - xcb-util-wm=0.4.2
  - xkeyboard-config=2.44
  - xorg-libice=1.1.2
  - xorg-libsm=1.2.6
  - xorg-libx11=1.8.12
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xorg-libxext=1.3.6
  - xorg-libxfixes=6.0.1
  - xorg-libxrandr=1.5.4
  - xorg-libxrender=0.9.12
  - xorg-libxshmfence=1.3.3
  - xorg-libxxf86vm=1.1.6
  - xorg-xorgproto=2024.1
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.21.0
  - zlib=1.3.1
  - zstd=1.5.7
  - pip:
      - efficientunet-pytorch==0.0.6
      - ipywidgets==8.1.8
      - jupyterlab-widgets==3.0.16
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.10.2.21
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.7.1
      - nvidia-nccl-cu12==2.27.3
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - opencv-python==4.12.0.88
      - protobuf==6.33.0
      - tensorboardx==2.6.4
      - torch==2.8.0+cu126
      - torchsummary==1.5.1
      - torchvision==0.23.0+cu126
      - triton==3.4.0
      - widgetsnbextension==4.0.15
prefix: /home/s2036401/miniconda3/envs/elm-gpu
